steps:
  # Step 1: Build the JAR
  - name: 'maven:3.9-eclipse-temurin-17'
    entrypoint: 'mvn'
    args: ['clean', 'package', '-DskipTests']

  # Step 2: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'asia-south1-docker.pkg.dev/vyaparsathi-backend/cloud-run-source-deploy/vyaparsathi-backend-service:$COMMIT_SHA',
        '.'
      ]

  # Step 3: Push the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'asia-south1-docker.pkg.dev/vyaparsathi-backend/cloud-run-source-deploy/vyaparsathi-backend-service:$COMMIT_SHA'
      ]

  # Step 4: Deploy Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - run
      - deploy
      - vyaparsathi-backend-service
      - --image
      - asia-south1-docker.pkg.dev/vyaparsathi-backend/cloud-run-source-deploy/vyaparsathi-backend-service:$COMMIT_SHA
      - --platform
      - managed
      - --region
      - asia-south1
      - --service-account
      - vyaparsathi-backend-sa@vyaparsathi-backend.iam.gserviceaccount.com
      - --add-cloudsql-instances
      - vyaparsathi-backend:asia-south1:vyaparsathi-db
      - --set-env-vars
      - SPRING_PROFILES_ACTIVE=prod
      - --set-secrets
      - SPRING_DATASOURCE_USERNAME=db-username:latest
      - --set-secrets
      - SPRING_DATASOURCE_PASSWORD=db-password:latest
      - --set-secrets
      - SPRING_MAIL_USERNAME=email-username:latest
      - --set-secrets
      - SPRING_MAIL_PASSWORD=email-password:latest
      - --set-secrets
      - APP_ALLOWED_ORIGINS=app-allowed-origin:latest
      - --set-secrets
      - JWT_SECRET=jwt-secret:latest
      - --allow-unauthenticated

images:
  - asia-south1-docker.pkg.dev/vyaparsathi-backend/cloud-run-source-deploy/vyaparsathi-backend-service:$COMMIT_SHA

options:
  logging: CLOUD_LOGGING_ONLY
