version: '3.8'

services:

  mysql:
    image: mysql:8.4
    container_name: vyaparsathi-mysql
    platform: linux/arm64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: vyaparsathi@123
      MYSQL_DATABASE: vyaparsathi_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - vyaparsathi-network

  vyaparsathi-backend:
    image: asia-south1-docker.pkg.dev/vyaparsathi-backend/cloud-run-source-deploy/vyaparsathi-backend-service:latest
    platform: linux/amd64
    container_name: vyaparsathi-backend
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: dev
      PORT: 8080

      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/vyaparsathi_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: vyaparsathi@123

      JWT_SECRET: local-dev-secret-change-in-prod

    networks:
      - vyaparsathi-network

networks:
  vyaparsathi-network:
    driver: bridge

volumes:
  mysql-data:
