package com.desitech.vyaparsathi.sales.service.invoice;

import com.lowagie.text.BadElementException;
import com.lowagie.text.*;
import com.lowagie.text.Font;
import com.lowagie.text.Image;
import com.lowagie.text.pdf.ColumnText;
import com.lowagie.text.pdf.PdfContentByte;
import com.lowagie.text.pdf.PdfPageEventHelper;
import com.lowagie.text.pdf.PdfWriter;

import java.awt.*;
import java.io.IOException;

public class InvoicePageEvent extends PdfPageEventHelper {

    private final Image logo;
    private final Font footerFont;

    public InvoicePageEvent(String logoPath) throws IOException, BadElementException {
        this.logo = Image.getInstance(logoPath);
        this.logo.scaleToFit(70, 70);
        this.logo.setAlignment(Element.ALIGN_LEFT);
        this.footerFont = new Font(Font.HELVETICA, 8, Font.ITALIC, Color.GRAY);
    }

    @Override
    public void onEndPage(PdfWriter writer, Document document) {
        PdfContentByte cb = writer.getDirectContent();

        // 1. Add footer watermark text
        Phrase footer = new Phrase("Generated by DesiTech Solutions India Pvt Ltd", footerFont);
        ColumnText.showTextAligned(cb, Element.ALIGN_CENTER,
                footer,
                (document.right() - document.left()) / 2 + document.leftMargin(),
                document.bottom() - 10, 0);

        // 2. Add page number
        String pageText = "Page " + writer.getPageNumber();
        ColumnText.showTextAligned(cb, Element.ALIGN_RIGHT,
                new Phrase(pageText, footerFont),
                document.right(), document.bottom() - 10, 0);
    }

    @Override
    public void onStartPage(PdfWriter writer, Document document) {
        try {
            logo.scaleToFit(60, 60);
            logo.setAbsolutePosition(document.leftMargin(), document.top() + 20);
            writer.getDirectContent().addImage(logo);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }


}