package com.desitech.vyaparsathi.sales.entity;

import com.desitech.vyaparsathi.sales.enums.OfflineSalesStatus;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * OfflineSalesQueue Entity
 *
 * Stores offline sales that need to be processed and synced to the backend.
 * Each offline sale is identified by a unique clientTxnId (generated by frontend).
 *
 * Status flow:
 *   DRAFT     → Just received from frontend
 *   PENDING   → Queued for processing
 *   PROCESSING → Currently being processed
 *   COMPLETED → Sale created + invoice generated
 *   FAILED    → Network/validation error (retryable)
 *   CONFLICT  → Duplicate or data conflict (manual review)
 */
@Entity
@Table(
    name = "offline_sales_queue",
    uniqueConstraints = {
        @UniqueConstraint(
            name = "uk_offline_sales_queue_shop_client_txn",
            columnNames = {"shop_id", "client_txn_id"}
        )
    },
    indexes = {
        @Index(name = "idx_offline_sales_shop_status", columnList = "shop_id,status"),
        @Index(name = "idx_offline_sales_user_status", columnList = "user_id,status"),
        @Index(name = "idx_offline_sales_device_id", columnList = "device_id"),
        @Index(name = "idx_offline_sales_created_at", columnList = "created_at"),
        @Index(name = "idx_offline_sales_status", columnList = "status")
    }
)
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class OfflineSalesQueue {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "shop_id", nullable = false)
    private Long shopId;

    @Column(name = "user_id", nullable = false, length = 100)
    private String userId;

    @Column(name = "client_txn_id", nullable = false, length = 100)
    private String clientTxnId;

    @Column(name = "device_id", nullable = false, length = 100)
    private String deviceId;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 30)
    private OfflineSalesStatus status;

    @Column(name = "offline_sale_no", length = 100)
    private String offlineSaleNo;

    /**
     * Full sale data as JSON from frontend
     * Stored as-is for replay processing
     */
    @Lob
    @Column(name = "request_payload_json", nullable = false, columnDefinition = "LONGTEXT")
    private String requestPayloadJson;

    /**
     * Server-generated sale ID after processing
     * Used to link queued record to actual sale
     */
    @Column(name = "sale_id")
    private Long saleId;

    /**
     * Invoice number generated after successful sale processing
     */
    @Column(name = "invoice_number", length = 100)
    private String invoiceNumber;

    /**
     * Signed URL for invoice download
     */
    @Column(name = "invoice_signed_url", length = 1000)
    private String invoiceSignedUrl;

    /**
     * Error tracking for debugging and retry logic
     */
    @Column(name = "error_code", length = 100)
    private String errorCode;

    @Column(name = "error_message", length = 1000)
    private String errorMessage;

    @Column(name = "retry_count", nullable = false)
    private Integer retryCount = 0;

    /**
     * When this sale was processed and synced
     */
    @Column(name = "synced_at")
    private LocalDateTime syncedAt;

    /**
     * Additional metadata (for debugging, metrics, etc.)
     */
    @Lob
    @Column(name = "metadata_json", columnDefinition = "LONGTEXT")
    private String metadataJson;

    @Column(name = "created_by")
    private Long createdBy;

    @Column(name = "updated_by")
    private Long updatedBy;

    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    @PrePersist
    public void prePersist() {
        LocalDateTime now = LocalDateTime.now();
        if (this.createdAt == null) {
            this.createdAt = now;
        }
        if (this.updatedAt == null) {
            this.updatedAt = now;
        }
        if (this.retryCount == null) {
            this.retryCount = 0;
        }
        if (this.status == null) {
            this.status = OfflineSalesStatus.DRAFT;
        }
    }

    @PreUpdate
    public void preUpdate() {
        this.updatedAt = LocalDateTime.now();
    }
}
