CREATE TABLE gst_hsn_master (
    id             BIGINT        NOT NULL AUTO_INCREMENT,
    hsn_code       VARCHAR(10)   NOT NULL,
    description    TEXT          NOT NULL,
    gst_type       VARCHAR(10)   NOT NULL DEFAULT 'GOODS',
    default_rate   DECIMAL(5,2)  NOT NULL DEFAULT 18.00,
    default_uqc    VARCHAR(10)   NOT NULL DEFAULT 'OTH',
    effective_from DATE,
    effective_to   DATE,
    PRIMARY KEY (id),
    UNIQUE KEY uq_hsn_code (hsn_code)
);

INSERT INTO gst_hsn_master (hsn_code, description, gst_type, default_rate, default_uqc) VALUES
('0401',   'Milk and cream, not concentrated nor sweetened',              'GOODS',    0.00, 'LTR'),
('1001',   'Wheat and meslin',                                             'GOODS',    0.00, 'KGS'),
('1006',   'Rice',                                                         'GOODS',    0.00, 'KGS'),
('1701',   'Cane or beet sugar',                                           'GOODS',    5.00, 'KGS'),
('2106',   'Food preparations not elsewhere specified',                    'GOODS',   18.00, 'KGS'),
('2201',   'Waters, including natural or artificial mineral waters',       'GOODS',   18.00, 'LTR'),
('2202',   'Waters, sweetened or flavoured',                               'GOODS',   28.00, 'LTR'),
('3004',   'Medicaments for therapeutic or prophylactic uses',             'GOODS',   12.00, 'NOS'),
('3401',   'Soap and organic surface-active products',                     'GOODS',   18.00, 'KGS'),
('4820',   'Registers, account books, notebooks',                          'GOODS',   12.00, 'NOS'),
('6105',   'Men''s or boys'' shirts, knitted or crocheted',                'GOODS',   12.00, 'PCS'),
('6109',   'T-shirts, singlets and other vests, knitted',                  'GOODS',   12.00, 'PCS'),
('6110',   'Jerseys, pullovers and sweatshirts, knitted',                  'GOODS',   12.00, 'PCS'),
('6203',   'Men''s or boys'' suits, ensembles, jackets, trousers',         'GOODS',   12.00, 'PCS'),
('6204',   'Women''s or girls'' suits, ensembles, jackets, dresses',       'GOODS',   12.00, 'PCS'),
('6401',   'Waterproof footwear with outer soles of rubber',               'GOODS',   18.00, 'PRS'),
('6403',   'Footwear with outer soles of rubber, leather uppers',          'GOODS',   18.00, 'PRS'),
('7113',   'Articles of jewellery and parts thereof, of precious metal',   'GOODS',    3.00, 'GMS'),
('7117',   'Imitation jewellery',                                          'GOODS',    3.00, 'GMS'),
('8471',   'Automatic data-processing machines (computers)',               'GOODS',   18.00, 'PCS'),
('8517',   'Telephone sets including smartphones',                         'GOODS',   18.00, 'PCS'),
('8518',   'Microphones, loudspeakers, headphones and earphones',          'GOODS',   18.00, 'PCS'),
('8528',   'Monitors, projectors and television receivers',                'GOODS',   28.00, 'PCS'),
('8544',   'Insulated wire, cable and other insulated electric conductors','GOODS',   18.00, 'KGS'),
('9608',   'Ball point pens, markers, highlighters and felt tipped pens',  'GOODS',   12.00, 'NOS'),
('996311', 'Food and beverage serving services',                           'SERVICES', 5.00, 'OTH'),
('997211', 'Renting of residential property',                              'SERVICES', 0.00, 'OTH'),
('998211', 'Legal advisory and representation services',                   'SERVICES',18.00, 'OTH'),
('998311', 'Management consulting and management services',                'SERVICES',18.00, 'OTH'),
('998361', 'Support services to agriculture, hunting and forestry',        'SERVICES',18.00, 'OTH'),
('999311', 'Primary education services',                                   'SERVICES', 0.00, 'OTH'),
('999714', 'Health-care services by a clinical establishment',             'SERVICES', 0.00, 'OTH');
